language: cpp

matrix:
  include:
     - { os: linux, env: PYTHON_VERSION=2.7 }
     - { os: linux, env: PYTHON_VERSION=2.7 MINICONDA_IN_AMBERHOME=True}
     - { os: linux, env: PYTHON_VERSION=2.7 MINICONDA_WILL_BE_INSTALLED=True}
     - { os: linux, env: PYTHON_VERSION=2.7 USE_WITH_PYTHON=True}
     - { os: linux, env: PYTHON_VERSION=2.7 SKIP_PYTHON=True}
     - { os: linux, env: PYTHON_VERSION=2.7 USE_AMBER_PREFIX=True}
     - { os: linux, env: PYTHON_VERSION=3.5 } 

sudo: true

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - gfortran
    - unzip

before_install:
    - source devtools/ci/setup_env.sh
    - source devtools/ci/install_parmed.sh # always install after AmberTools

install:
    - source devtools/ci/install_pdb4amber.sh # always install after AmberTools

script:
    - reduce -Version
    - tleap -h
    - which AddToBox
    - source devtools/ci/run_tests.sh

after_success:
    - echo "Congrats"

notifications:
  email: false
