language: cpp

matrix:
  include:
     - { os: linux, env: PYTHON_VERSION=2.7 } 

sudo: true

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - gfortran
    - cmake
    - unzip
    - csh
    - flex
    - patch
    - openmpi-bin
    - openmpi-common
    - libopenmpi-dev

install:
    - echo "TRAVIS_BUILD_DIR $TRAVIS_BUILD_DIR"
    - source devtools/ci/load_functions.sh
    - download_ambertools
    - install_ambertools_travis

script:
    - run_tests

after_success:
    - echo "Congrats. Happy computing"

notifications:
  email: false
